"""Sealed cards: state the host holds but cannot read.

Invite-code play has no server, so one player's machine runs the match — and
today that machine holds every deck order and every hand in the clear
(:class:`~.state.GameState`). The encrypted shuffle in ``webapp/js/mentalpoker.js``
removes the need to trust it, but only if the rules runtime never sees the
cards. That is what a *sealed* card is: a handle to a position in a deck whose
contents are shared out among the players, and which the host can move between
zones — draw it, discard it, shuffle it back — without ever learning what it is.

    ``#1-14``  =  seat 1's deck, ciphertext position 14

Handles are public on purpose. Positions carry no information: the order was
decided by the shuffle protocol, so a permutation of handles leaks nothing and
the engine can keep dealing, drawing and reshuffling exactly as it does now.
Only *opening* a handle needs the other players' keys.

**Loud, not lenient.** :func:`catalog.card` raises :class:`SealedCardError` for a
handle rather than returning a blank card. A rule that needs an identity the
host is not allowed to have must stop and ask for a reveal; the one thing it
must never do is quietly decide that a hidden card is not a Human, has no
subtype, or costs zero. Every such stop is a place the reveal protocol has to
cover, and the exception is how they are found.

**The verification half.** The prover lives in the browser (``mentalpoker.js``);
this module is the checker. When a player claims that position 14 holds a
particular card, they publish the keys that open it, and :func:`verify_reveal`
recomputes the claim from the ciphertext the table committed to at the deal.
The maths mirrors the JS exactly — same group, same card encoding — and
``tests/test_sealed.py`` pins the two together against vectors generated by the
JS itself, because a subtle disagreement here would not break anything visibly:
it would just quietly stop catching liars.
"""
from __future__ import annotations

from typing import Any, Iterable, Mapping, Sequence

SEAL_PREFIX = "#"


class SealedCardError(LookupError):
    """A rule asked for the identity of a card the host cannot read.

    Not a bug on its own: it is the engine refusing to guess. The caller either
    reveals the card first (the owner publishes the keys that open it) or the
    rule genuinely cannot run on hidden information.
    """

    def __init__(self, card_id: str):
        super().__init__(
            f"{card_id} is sealed: the host does not hold this card's identity. "
            "It has to be revealed before a rule can read it."
        )
        self.card_id = card_id


def seal(seat_idx: int, position: int) -> str:
    """The handle for `position` in the seat's sealed pile."""
    return f"{SEAL_PREFIX}{int(seat_idx)}-{int(position)}"


def is_sealed(card_id: str) -> bool:
    return isinstance(card_id, str) and card_id.startswith(SEAL_PREFIX)


def sealed_seat(card_id: str) -> int:
    """Which seat's deck a handle came from — the one zone fact it does carry.

    Ownership decides where a card returns to when it leaves play, and that is
    fixed by the decklist, so it stays readable while the card does not.
    """
    return _parse(card_id)[0]


def sealed_position(card_id: str) -> int:
    return _parse(card_id)[1]


def _parse(card_id: str) -> tuple[int, int]:
    if not is_sealed(card_id):
        raise ValueError(f"{card_id!r} is not a sealed card")
    try:
        seat, position = card_id[len(SEAL_PREFIX):].split("-", 1)
        return int(seat), int(position)
    except ValueError:
        raise ValueError(f"{card_id!r} is not a valid sealed handle") from None


def sealed_pile(seat_idx: int, size: int) -> tuple[str, ...]:
    """A seat's whole pile as handles, in committed ciphertext order.

    The order looks like identity order and is not: the shuffle happened inside
    the protocol, before any of this. Position 0 is simply the first ciphertext
    every player agreed on.
    """
    return tuple(seal(seat_idx, position) for position in range(size))


def reveal_request(card_id: str) -> dict[str, Any]:
    """What the table has to open before a rule that reached this card can run.

    One shape for every stop — a tutor, a random discard, a look at the top of a
    deck — so a client answers them all the same way (publish the keys for this
    position, then retry) without having to know which cards read what.
    """
    seat, position = _parse(card_id)
    return {"card_id": card_id, "seat": seat, "position": position}


# --------------------------------------------------------------------------
# Verification — the checking half of webapp/js/mentalpoker.js
# --------------------------------------------------------------------------

# RFC 3526 group 5, the same 1536-bit safe prime the browser works in. Both
# sides must agree to the digit: a mismatch would not fail loudly, it would
# just make every reveal unverifiable.
P = int(
    "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74"
    "020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437"
    "4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED"
    "EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF05"
    "98DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB"
    "9ED529077096966D670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFF",
    16,
)
Q = (P - 1) // 2


def card_value(index: int) -> int:
    """The group element standing for pile index `index`.

    Squaring keeps it a quadratic residue, i.e. inside the prime-order subgroup
    where the players' keys commute — the property the whole protocol rests on.
    """
    base = index + 2
    return (base * base) % P


def _exponent(key: Any) -> int:
    """A published key, however it arrived: {'d': ...} from the wire, or an int.

    Only the decryption exponent is ever needed to check a reveal; a key that
    arrives without one is unusable, not merely incomplete.
    """
    if isinstance(key, Mapping):
        if "d" not in key:
            raise ValueError("Published key has no decryption exponent")
        return int(key["d"])
    return int(key)


def peel(cipher: int, keys: Iterable[Any]) -> int:
    """Strip published keys off a ciphertext, in any order (they commute)."""
    value = int(cipher) % P
    for key in keys:
        value = pow(value, _exponent(key), P)
    return value


def open_index(cipher: int, keys: Iterable[Any], pile_size: int) -> int:
    """The pile index a ciphertext opens to, or -1 if it is not a card at all."""
    value = peel(cipher, keys)
    for index in range(pile_size):
        if card_value(index) == value:
            return index
    return -1


def verify_reveal(cipher: int, keys: Iterable[Any], claimed_index: int) -> bool:
    """Is the claim what the committed ciphertext actually opens to?

    This is what makes a reveal something other than a player's word: it is
    recomputed from the ciphertext the whole table committed to at the deal and
    the keys they published, so a lie has to survive arithmetic rather than
    trust.
    """
    return peel(cipher, keys) == card_value(int(claimed_index))


def audit_pile(
    ciphers: Sequence[int],
    keys_by_position: Sequence[Sequence[Any]],
    pile_size: int,
) -> tuple[bool, str]:
    """End-of-match check: every position opens, and to each card exactly once.

    A dishonest shuffler cannot choose where a card lands — the values it
    permutes are already encrypted under everybody else's keys — but nothing so
    far stops it duplicating a position. Once every key is published that shows
    up here as a card seen twice.
    """
    if len(ciphers) != len(keys_by_position):
        return False, "a key set is missing for some position"
    seen = [0] * pile_size
    for position, cipher in enumerate(ciphers):
        index = open_index(cipher, keys_by_position[position], pile_size)
        if index < 0:
            return False, f"position {position} does not open to a card in this deck"
        seen[index] += 1
    # Report a duplicate before a missing card: one card in two places is the
    # tampering this catches, and it always shows up as some other card missing
    # too, which on its own would be the less telling half of the story.
    for index, count in enumerate(seen):
        if count > 1:
            return False, f"pile index {index} appears {count} times, expected once"
    for index, count in enumerate(seen):
        if count != 1:
            return False, f"pile index {index} appears {count} times, expected once"
    return True, ""
