export function getUiElements() {
    return {
        deckA: document.getElementById('deckA'),
        deckB: document.getElementById('deckB'),
        checkpointPath: document.getElementById('checkpointPath'),
        btnNewGame: document.getElementById('btnNewGame'),
        btnEndTurn: document.getElementById('btnEndTurn'),
        mulliganPanel: document.getElementById('mulliganPanel'),
        mulliganInfo: document.getElementById('mulliganInfo'),
        status: document.getElementById('status'),
        vpSidebar: document.getElementById('vpSidebar'),
        actionHistory: document.getElementById('actionHistory'),
        hud: document.getElementById('hud'),
        pending: document.getElementById('pending'),
        lanes: document.getElementById('lanes'),
        hand: document.getElementById('hand'),
        yourMana: document.getElementById('yourMana'),
        oppMana: document.getElementById('oppMana'),
        oppHand: document.getElementById('oppHand'),
        yourUnderworld: document.getElementById('yourUnderworld'),
        oppUnderworld: document.getElementById('oppUnderworld'),
        yourDeckCount: document.getElementById('yourDeckCount'),
        oppDeckCount: document.getElementById('oppDeckCount'),
        choiceModal: document.getElementById('choiceModal'),
        choiceTitle: document.getElementById('choiceTitle'),
        choicePrompt: document.getElementById('choicePrompt'),
        choiceSub: document.getElementById('choiceSub'),
        choiceOptions: document.getElementById('choiceOptions'),
    };
}
